name : Build
on : [pull_request_target]

jobs:
  deploy-ic:
    name: "Deploy to IC"
    runs-on: ubuntu-latest
    concurrency:
      group: "website update"
      cancel-in-progress: true
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      
      - run: git submodule update --init
      
      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install DFX
        uses: dfinity/setup-dfx@main
        with:
          dfx-version: "0.22.0"


      - name: Install Dependencies
        run: npm install

      - name: Create Build
        run: dfx deploy
